---
title: "RQ1-1: Correlation Analysis with Stock, World, Commodity Indices"
author: "CS564 Team 10"
output: 
  html_notebook: 
    fig_width: 7
    fig_height: 7
    fig_caption: yes
editor_options: 
  chunk_output_type: console
---

Load Datasets

```{r}
suppressMessages(library(data.table))
suppressMessages(library(readxl))
suppressMessages(library(dplyr))
suppressMessages(library(stringr))
suppressMessages(library(ggplot2))
suppressMessages(library(ggcorrplot))
suppressMessages(library(tidyr))
suppressMessages(library(rstatix))


set.seed(7)
theme_set(theme_bw())
theme_settings <- theme(
  axis.title.x = element_text(angle = 0, color = "black"), 
  axis.title.y = element_text(angle = 90, color = "black"),
  axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1, size = 10),
  axis.text.y = element_text(size = 10),
)
center_title <- theme(
  plot.title = element_text(hjust = 0.5)
)

# Metadata
coin_features <- fread("datasets/coin_features.csv") %>% as.data.frame()
ticker_info <- fread("datasets/ticker_info.csv") %>% as.data.frame()
```

Pre-COVID19

```{r}

ndays <- 12
prices <- data.frame(matrix(nrow = ndays, ncol = 0))
changes <- data.frame(matrix(nrow = ndays, ncol = 0))
returns <- data.frame(matrix(nrow = ndays, ncol = 0))
volatility <- data.frame(matrix(nrow = ndays, ncol = 0))

price_cols <- c("Date", "Close", "Volume", "change", "returns", "volatility")
for (fname in list.files(paste("datasets/monthly/coins", sep = "/"))) {
  symbol <- str_split(fname, "-", simplify = T)[1]
  values <- fread(paste("datasets/monthly/coins", fname, sep = "/")) %>% filter(Date >= "2019-01-01" & Date <= "2019-12-31") %>% select(all_of(price_cols)) %>% arrange(Date) %>% fill(everything(), .direction = "downup") %>% select_if(colSums(!is.na(.)) > 0)

  volatility$Date <- values$Date
  volatility[symbol] <- values$volatility
}

prices.tech <- prices
changes.tech <- changes
returns.tech <- returns
volatility.tech <- volatility
for (fname in list.files(paste("datasets/monthly/tech", sep = "/"))) {
  symbol <- str_split(fname, "\\.", simplify = T)[1]
  values <- fread(paste("datasets/monthly/tech/", fname, sep = "/")) %>% filter(Date >= "2019-01-01" & Date <= "2019-12-31") %>% select(all_of(price_cols)) %>% arrange(Date) %>% as.data.frame()
  
  volatility.tech <- inner_join(x = volatility.tech, y = values[c("Date", "volatility")], by = "Date") %>% fill(everything(), .direction = "downup") %>% select_if(colSums(!is.na(.)) > 0)
  names(volatility.tech)[length(volatility.tech)] <- symbol
}

prices.indices<- prices
changes.indices <- changes
returns.indices <- returns
volatility.indices <- volatility
for (fname in list.files(paste("datasets/monthly/indices", sep = "/"))) {
  symbol <- str_split(fname, "\\.", simplify = T)[1]
  values <- fread(paste("datasets/monthly/indices/", fname, sep = "/")) %>% filter(Date >= "2019-01-01" & Date <= "2019-12-31") %>% select(all_of(price_cols)) %>% arrange(Date) %>% as.data.frame()

  
  volatility.indices <- inner_join(x = volatility.indices, y = values[c("Date", "volatility")], by = "Date") %>% fill(everything(), .direction = "downup") %>% select_if(colSums(!is.na(.)) > 0)
  names(volatility.indices)[length(volatility.indices)] <- symbol
}

# prices.sp500 <- prices
# changes.sp500 <- changes
# returns.sp500 <- returns
# for (fname in list.files(paste("datasets/monthly/S&P_500", sep = "/"))) {
#   symbol <- str_split(fname, "\\.", simplify = T)[1]
#   values <- fread(paste("datasets/monthly/S&P_500", fname, sep = "/")) %>% filter(Date >= "2019-01-01" & Date <= "2019-12-31") %>% select(all_of(price_cols)) %>% arrange(Date) %>% as.data.frame()
# 
#   # join with Date of coins
#   prices.sp500 <- inner_join(x = prices.sp500, y = values[c("Date", "Close")], by = "Date") %>% fill(everything(), .direction = "downup") %>% select_if(colSums(!is.na(.)) > 0)
#   names(prices.sp500)[length(prices.sp500)] <- symbol
# 
#   changes.sp500 <- inner_join(x = changes.sp500, y = values[c("Date", "change")], by = "Date") %>% fill(everything(), .direction = "downup") %>% select_if(colSums(!is.na(.)) > 0)
#   names(changes.sp500)[length(changes.sp500)] <- symbol
# 
#   returns.sp500 <- inner_join(x = returns.sp500, y = values[c("Date", "returns")], by = "Date") %>% fill(everything(), .direction = "downup") %>% select_if(colSums(!is.na(.)) > 0)
#   names(returns.sp500)[length(returns.sp500)] <- symbol
# }

# Correlation Analysis
for (aspect in c("volatility")) {
  for (factor in c("tech", "indices")) {
    aspect.data <- get(aspect)[-1]
    cor.data <- get(paste(aspect, factor, sep = "."))[-1]
    cor.matrix <- cor_mat(cor.data)
    cor.matrix <- cor.matrix %>% select(c("rowname", names(aspect.data))) %>% filter(!rowname %in% names(aspect.data))
    attr(cor.matrix, "pvalue") <- attr(cor.matrix, "pvalue") %>% select(c("rowname", names(aspect.data))) %>% filter(!rowname %in% names(aspect.data))
    assign(paste(aspect, factor, "corr", sep = "."), cor.matrix)
    
    # cor.fname <- paste(aspect, factor, "correlation-2019.csv", sep = "-")
    # p.fname <- paste(aspect, factor, "pvalue-2019.csv", sep = "-")
    # write.csv(cor.matrix, paste("results", cor.fname, sep = "/"))
    # write.csv(attr(cor.matrix, "pvalue"), paste("results", p.fname, sep = "/"))
    
    ts.data <- get(paste(aspect, factor, sep = "."))
    ts.data[-1] <- scale(ts.data[-1])
    melt.data <- reshape2::melt(ts.data, "Date", value.name = "Values", variable.name = "Ticker")
    assign(paste(aspect, factor, "melt", sep = "."), melt.data)
    
    ts.fname <- paste(aspect, factor, "ts-2019.csv", sep = "-")
    # write.csv(ts.data, paste("results", ts.fname, sep = "/"))
    
    print(paste(aspect, factor, "ended!"))
  }
}

# Visualization
for (aspect in c("volatility")) {
  for (factor in c("tech", "indices")) {
    # melt.data <- get(paste(aspect, factor, "melt", sep = "."))
    # ts.chart <- ggplot(data = melt.data, aes(x = Date, y = Values, color = Ticker)) +
    #   ggtitle(paste("Movement of", aspect)) +
    #   geom_line() + 
    #   center_title +
    #   guides(col = guide_legend(ncol = 20)) +
    #   theme(legend.position = "bottom", legend.direction = "vertical")
    
    cor.matrix <- get(paste(aspect, factor, "corr", sep = "."))
    cor.chart <- ggcorrplot(cor.matrix, pch.cex = 1) + labs(x = "Ticker", y = "Cryptocurrency") + ggtitle(paste("Correlation in", aspect, "(2019)")) + theme_settings + center_title
    cor.dense <- ggplot(data = cor_gather(cor.matrix), aes(x = cor)) + 
      geom_density(color = 2, size = 1.5) +
      labs(x = "Correlation Coefficient", y = "Density") +
      ggtitle(paste("Density Plot of Correlation in", factor, aspect, "(2019)"))
      center_title

    # assign(paste(aspect, factor, "ts.chart.pre", sep = "."), ts.chart)
    # assign(paste(aspect, factor, "cor.chart.pre", sep = "."), cor.chart)
    
    # ts.plotname <- paste(aspect, factor, "ts-chart-2019.png", sep = "-")
    # cor.plotname <- paste(aspect, factor, "cor-chart-2019.png", sep = "-")
    
    # ggsave(paste("visualizations", ts.plotname, sep = "/"), ts.chart)
    # ggsave(paste("visualizations", cor.plotname, sep = "/"), cor.chart)
    
    print(cor.dense)
    print(cor.chart)
  }
}

```

Peri-COVID19

```{r}

ndays <- 12
prices <- data.frame(matrix(nrow = ndays, ncol = 0))
changes <- data.frame(matrix(nrow = ndays, ncol = 0))
returns <- data.frame(matrix(nrow = ndays, ncol = 0))
volatility <- data.frame(matrix(nrow = ndays, ncol = 0))

price_cols <- c("Date", "Close", "Volume", "change", "returns", "volatility")
for (fname in list.files(paste("datasets/monthly/coins", sep = "/"))) {
  symbol <- str_split(fname, "-", simplify = T)[1]
  values <- fread(paste("datasets/monthly/coins", fname, sep = "/")) %>% filter(Date >= "2020-01-01" & Date <= "2020-12-31") %>% select(all_of(price_cols)) %>% arrange(Date) %>% fill(everything(), .direction = "downup") %>% select_if(colSums(!is.na(.)) > 0)

  volatility$Date <- values$Date
  volatility[symbol] <- values$volatility
}

prices.tech <- prices
changes.tech <- changes
returns.tech <- returns
volatility.tech <- volatility

for (fname in list.files(paste("datasets/monthly/tech", sep = "/"))) {
  symbol <- str_split(fname, "\\.", simplify = T)[1]
  values <- fread(paste("datasets/monthly/tech/", fname, sep = "/")) %>% filter(Date >= "2020-01-01" & Date <= "2020-12-31") %>% select(all_of(price_cols)) %>% arrange(Date) %>% as.data.frame()
  
  volatility.tech <- inner_join(x = volatility.tech, y = values[c("Date", "volatility")], by = "Date") %>% fill(everything(), .direction = "downup") %>% select_if(colSums(!is.na(.)) > 0)
  names(volatility.tech)[length(volatility.tech)] <- symbol
}

prices.indices<- prices
changes.indices <- changes
returns.indices <- returns
volatility.indices <- volatility
for (fname in list.files(paste("datasets/monthly/indices", sep = "/"))) {
  symbol <- str_split(fname, "\\.", simplify = T)[1]
  values <- fread(paste("datasets/monthly/indices/", fname, sep = "/")) %>% filter(Date >= "2020-01-01" & Date <= "2020-12-31") %>% select(all_of(price_cols)) %>% arrange(Date) %>% as.data.frame()
  
  volatility.indices <- inner_join(x = volatility.indices, y = values[c("Date", "volatility")], by = "Date") %>% fill(everything(), .direction = "downup") %>% select_if(colSums(!is.na(.)) > 0)
  names(volatility.indices)[length(volatility.indices)] <- symbol
}

# prices.sp500 <- prices
# changes.sp500 <- changes
# returns.sp500 <- returns
# for (fname in list.files(paste("datasets/monthly/S&P_500", sep = "/"))) {
#   symbol <- str_split(fname, "\\.", simplify = T)[1]
#   values <- fread(paste("datasets/monthly/S&P_500", fname, sep = "/")) %>% filter(Date >= "2020-01-01" & Date <= "2020-12-31") %>% select(all_of(price_cols)) %>% arrange(Date) %>% as.data.frame()
# 
#   # join with Date of coins
#   prices.sp500 <- inner_join(x = prices.sp500, y = values[c("Date", "Close")], by = "Date") %>% fill(everything(), .direction = "downup") %>% select_if(colSums(!is.na(.)) > 0)
#   names(prices.sp500)[length(prices.sp500)] <- symbol
# 
#   changes.sp500 <- inner_join(x = changes.sp500, y = values[c("Date", "change")], by = "Date") %>% fill(everything(), .direction = "downup") %>% select_if(colSums(!is.na(.)) > 0)
#   names(changes.sp500)[length(changes.sp500)] <- symbol
# 
#   returns.sp500 <- inner_join(x = returns.sp500, y = values[c("Date", "returns")], by = "Date") %>% fill(everything(), .direction = "downup") %>% select_if(colSums(!is.na(.)) > 0)
#   names(returns.sp500)[length(returns.sp500)] <- symbol
# }

# Correlation Analysis
for (aspect in c("volatility")) {
  for (factor in c("tech", "indices")) {
    aspect.data <- get(aspect)[-1]
    cor.data <- get(paste(aspect, factor, sep = "."))[-1]
    cor.matrix <- cor_mat(cor.data)
    cor.matrix <- cor.matrix %>% select(c("rowname", names(aspect.data))) %>% filter(!rowname %in% names(aspect.data))
    attr(cor.matrix, "pvalue") <- attr(cor.matrix, "pvalue") %>% select(c("rowname", names(aspect.data))) %>% filter(!rowname %in% names(aspect.data))
    assign(paste(aspect, factor, "corr", sep = "."), cor.matrix)
    
    # cor.fname <- paste(aspect, factor, "correlation-2019.csv", sep = "-")
    # p.fname <- paste(aspect, factor, "pvalue-2019.csv", sep = "-")
    # write.csv(cor.matrix, paste("results", cor.fname, sep = "/"))
    # write.csv(attr(cor.matrix, "pvalue"), paste("results", p.fname, sep = "/"))
    
    ts.data <- get(paste(aspect, factor, sep = "."))
    ts.data[-1] <- scale(ts.data[-1])
    melt.data <- reshape2::melt(ts.data, "Date", value.name = "Values", variable.name = "Ticker")
    assign(paste(aspect, factor, "melt", sep = "."), melt.data)
    
    ts.fname <- paste(aspect, factor, "ts-2019.csv", sep = "-")
    # write.csv(ts.data, paste("results", ts.fname, sep = "/"))
    
    print(paste(aspect, factor, "ended!"))
  }
}

# Visualization
for (aspect in c("volatility")) {
  for (factor in c("tech", "indices")) {
    # melt.data <- get(paste(aspect, factor, "melt", sep = "."))
    # ts.chart <- ggplot(data = melt.data, aes(x = Date, y = Values, color = Ticker)) +
    #   ggtitle(paste("Movement of", aspect)) +
    #   geom_line() + 
    #   center_title +
    #   guides(col = guide_legend(ncol = 20)) +
    #   theme(legend.position = "bottom", legend.direction = "vertical")
    
    cor.matrix <- get(paste(aspect, factor, "corr", sep = "."))
    cor.chart <- ggcorrplot(cor.matrix, pch.cex = 1) + labs(x = "Ticker", y = "Cryptocurrency") + ggtitle(paste("Correlation in", aspect, "(2020)")) + theme_settings + center_title
    cor.dense <- ggplot(data = cor_gather(cor.matrix), aes(x = cor)) + 
      geom_density(color = 2, size = 1.5) +
      labs(x = "Correlation Coefficient", y = "Density") +
      ggtitle(paste("Density Plot of Correlation in", factor, aspect, "(2020)"))
      center_title

    # assign(paste(aspect, factor, "ts.chart.pre", sep = "."), ts.chart)
    # assign(paste(aspect, factor, "cor.chart.pre", sep = "."), cor.chart)
    
    # ts.plotname <- paste(aspect, factor, "ts-chart-2019.png", sep = "-")
    # cor.plotname <- paste(aspect, factor, "cor-chart-2019.png", sep = "-")
    
    # ggsave(paste("visualizations", ts.plotname, sep = "/"), ts.chart)
    # ggsave(paste("visualizations", cor.plotname, sep = "/"), cor.chart)
    
    print(cor.dense)
    print(cor.chart)
  }
}


```

Post-COVID19

```{r}

ndays <- 10
prices <- data.frame(matrix(nrow = ndays, ncol = 0))
changes <- data.frame(matrix(nrow = ndays, ncol = 0))
returns <- data.frame(matrix(nrow = ndays, ncol = 0))
volatility <- data.frame(matrix(nrow = ndays, ncol = 0))

price_cols <- c("Date", "Close", "Volume", "change", "returns", "volatility")
for (fname in list.files(paste("datasets/monthly/coins", sep = "/"))) {
  symbol <- str_split(fname, "-", simplify = T)[1]
  values <- fread(paste("datasets/monthly/coins", fname, sep = "/")) %>% filter(Date >= "2021-01-01" & Date <= "2021-12-31") %>% select(all_of(price_cols)) %>% arrange(Date) %>% fill(everything(), .direction = "downup") %>% select_if(colSums(!is.na(.)) > 0)

  volatility$Date <- values$Date
  volatility[symbol] <- values$volatility
}

prices.tech <- prices
changes.tech <- changes
returns.tech <- returns
volatility.tech <- volatility
for (fname in list.files(paste("datasets/monthly/tech", sep = "/"))) {
  symbol <- str_split(fname, "\\.", simplify = T)[1]
  values <- fread(paste("datasets/monthly/tech/", fname, sep = "/")) %>% filter(Date >= "2021-01-01" & Date <= "2021-12-31") %>% select(all_of(price_cols)) %>% arrange(Date) %>% as.data.frame()
  
  volatility.tech <- inner_join(x = volatility.tech, y = values[c("Date", "volatility")], by = "Date") %>% fill(everything(), .direction = "downup") %>% select_if(colSums(!is.na(.)) > 0)
  names(volatility.tech)[length(volatility.tech)] <- symbol
}

prices.indices<- prices
changes.indices <- changes
returns.indices <- returns
volatility.indices <- volatility
for (fname in list.files(paste("datasets/monthly/indices", sep = "/"))) {
  symbol <- str_split(fname, "\\.", simplify = T)[1]
  values <- fread(paste("datasets/monthly/indices/", fname, sep = "/")) %>% filter(Date >= "2021-01-01" & Date <= "2021-12-31") %>% select(all_of(price_cols)) %>% arrange(Date) %>% as.data.frame()
  
  volatility.indices <- inner_join(x = volatility.indices, y = values[c("Date", "volatility")], by = "Date") %>% fill(everything(), .direction = "downup") %>% select_if(colSums(!is.na(.)) > 0)
  names(volatility.indices)[length(volatility.indices)] <- symbol
}

# prices.sp500 <- prices
# changes.sp500 <- changes
# returns.sp500 <- returns
# for (fname in list.files(paste("datasets/monthly/S&P_500", sep = "/"))) {
#   symbol <- str_split(fname, "\\.", simplify = T)[1]
#   values <- fread(paste("datasets/monthly/S&P_500", fname, sep = "/")) %>% filter(Date >= "2020-01-01" & Date <= "2020-12-31") %>% select(all_of(price_cols)) %>% arrange(Date) %>% as.data.frame()
# 
#   # join with Date of coins
#   prices.sp500 <- inner_join(x = prices.sp500, y = values[c("Date", "Close")], by = "Date") %>% fill(everything(), .direction = "downup") %>% select_if(colSums(!is.na(.)) > 0)
#   names(prices.sp500)[length(prices.sp500)] <- symbol
# 
#   changes.sp500 <- inner_join(x = changes.sp500, y = values[c("Date", "change")], by = "Date") %>% fill(everything(), .direction = "downup") %>% select_if(colSums(!is.na(.)) > 0)
#   names(changes.sp500)[length(changes.sp500)] <- symbol
# 
#   returns.sp500 <- inner_join(x = returns.sp500, y = values[c("Date", "returns")], by = "Date") %>% fill(everything(), .direction = "downup") %>% select_if(colSums(!is.na(.)) > 0)
#   names(returns.sp500)[length(returns.sp500)] <- symbol
# }

# Correlation Analysis
for (aspect in c("volatility")) {
  for (factor in c("tech", "indices")) {
    aspect.data <- get(aspect)[-1]
    cor.data <- get(paste(aspect, factor, sep = "."))[-1]
    cor.matrix <- cor_mat(cor.data)
    cor.matrix <- cor.matrix %>% select(c("rowname", names(aspect.data))) %>% filter(!rowname %in% names(aspect.data))
    attr(cor.matrix, "pvalue") <- attr(cor.matrix, "pvalue") %>% select(c("rowname", names(aspect.data))) %>% filter(!rowname %in% names(aspect.data))
    assign(paste(aspect, factor, "corr", sep = "."), cor.matrix)
    
    # cor.fname <- paste(aspect, factor, "correlation-2019.csv", sep = "-")
    # p.fname <- paste(aspect, factor, "pvalue-2019.csv", sep = "-")
    # write.csv(cor.matrix, paste("results", cor.fname, sep = "/"))
    # write.csv(attr(cor.matrix, "pvalue"), paste("results", p.fname, sep = "/"))
    
    ts.data <- get(paste(aspect, factor, sep = "."))
    ts.data[-1] <- scale(ts.data[-1])
    melt.data <- reshape2::melt(ts.data, "Date", value.name = "Values", variable.name = "Ticker")
    assign(paste(aspect, factor, "melt", sep = "."), melt.data)
    
    ts.fname <- paste(aspect, factor, "ts-2019.csv", sep = "-")
    # write.csv(ts.data, paste("results", ts.fname, sep = "/"))
    
    print(paste(aspect, factor, "ended!"))
  }
}

# Visualization
for (aspect in c("volatility")) {
  for (factor in c("tech", "indices")) {
    # melt.data <- get(paste(aspect, factor, "melt", sep = "."))
    # ts.chart <- ggplot(data = melt.data, aes(x = Date, y = Values, color = Ticker)) +
    #   ggtitle(paste("Movement of", aspect)) +
    #   geom_line() + 
    #   center_title +
    #   guides(col = guide_legend(ncol = 20)) +
    #   theme(legend.position = "bottom", legend.direction = "vertical")
    
    cor.matrix <- get(paste(aspect, factor, "corr", sep = "."))
    cor.chart <- ggcorrplot(cor.matrix, pch.cex = 1) + labs(x = "Ticker", y = "Cryptocurrency") + ggtitle(paste("Correlation in", aspect, "(2021)")) + theme_settings + center_title
    cor.dense <- ggplot(data = cor_gather(cor.matrix), aes(x = cor)) + 
      geom_density(color = 2, size = 1.5) +
      labs(x = "Correlation Coefficient", y = "Density") +
      ggtitle(paste("Density Plot of Correlation in", factor, aspect, "(2021)"))
      center_title

    # assign(paste(aspect, factor, "ts.chart.pre", sep = "."), ts.chart)
    # assign(paste(aspect, factor, "cor.chart.pre", sep = "."), cor.chart)
    
    # ts.plotname <- paste(aspect, factor, "ts-chart-2019.png", sep = "-")
    # cor.plotname <- paste(aspect, factor, "cor-chart-2019.png", sep = "-")
    
    # ggsave(paste("visualizations", ts.plotname, sep = "/"), ts.chart)
    # ggsave(paste("visualizations", cor.plotname, sep = "/"), cor.chart)
    
    print(cor.dense)
    print(cor.chart)
  }
}

```
