---
title: "RQ2"
author: "CS564 Team 10"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r}
suppressMessages(library(data.table))
suppressMessages(library(readxl))
suppressMessages(library(dplyr))
suppressMessages(library(stringr))
suppressMessages(library(PerformanceAnalytics))
suppressMessages(library(ggcorrplot))
suppressMessages(library(ggplot2))
suppressMessages(library(tidyr))
suppressMessages(library(igraph))
suppressMessages(library(ggraph))
suppressMessages(library(rstatix))

set.seed(7)
theme_set(theme_bw())
theme_settings <- theme(
  axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1, size = 10),
  axis.text.y = element_text(size = 10),
)
center_title <- theme(
  plot.title = element_text(hjust = 0.5)
)

# Metadata
coin_features <- fread("datasets/coin_features.csv") %>% as.data.frame()
ticker_info <- fread("datasets/ticker_info.csv") %>% as.data.frame()
```


Pre-COVID19
```{r}

ndays <- 365
coins.prices <- data.frame(matrix(nrow = ndays, ncol = 0))
coins.changes <- data.frame(matrix(nrow = ndays, ncol = 0))
coins.returns <- data.frame(matrix(nrow = ndays, ncol = 0))
coins.volatility <- data.frame(matrix(nrow = ndays, ncol = 0))

price_cols <- c("Date", "Close", "Volume", "change", "returns", "volatility")
for (fname in list.files(paste("datasets/daily/coins", sep = "/"))) {
  symbol <- str_split(fname, "-", simplify = T)[1]
  values <- fread(paste("datasets/daily/coins", fname, sep = "/")) %>% as.data.frame() %>% filter(Date >= "2019-01-01" & Date <= "2019-12-31") %>% select(all_of(price_cols)) %>% arrange(Date)  %>% fill(everything(), .direction = "downup")

  if (!any(is.na(values$Close))) {
    coins.prices$Date <- values$Date
    coins.prices[symbol] <- values$Close 
    coins.changes[symbol] <- values$change
    coins.returns[symbol] <- values$returns
    coins.volatility[symbol] <- values$volatility
  }
}

# Coin Prices
coins.prices.corr <- round(cor(coins.prices[-1]), 2)
coins.prices.corr.p <- round(ggcorrplot::cor_pmat(coins.prices[-1]), 2)
ggcorrplot(coins.prices.corr, pch.cex = 1, p.mat = coins.prices.corr.p, title = "Correlation in Coin Prices (2019)") +
  theme_settings + center_title

select_coin <- "ETH"
coins.prices.cor.mat <- cor_mat(coins.prices[-1])
coins.prices.cor.list <- cor_gather(coins.prices.cor.mat)
net <- coins.prices.cor.list %>% filter(var1 == select_coin & var2 != select_coin & abs(cor) > 0.5) %>% graph_from_data_frame(directed = F)
net <- simplify(net, remove.multiple = F, remove.loops = T) 
V(net)[name == select_coin]$color <- "grey"
V(net)[name != select_coin]$color <- "white"
E(net)$width <- 2 * abs(E(net)$cor)
E(net)$color <- "white"
E(net)[cor < 0.5]$color <- "blue"
E(net)[cor > 0.5]$color <- "red"
E(net)[p > 0.05]$linestyle <- 2
plot(net, layout = layout.kamada.kawai)

coins.prices[-1] <- scale(coins.prices[-1])
coins.prices.melt <- reshape2::melt(coins.prices, "Date", value.name = "Prices", variable.name = "Coins")
ggplot(data = coins.prices.melt, aes(x = Date, y = Prices, color = Coins)) +
      ggtitle(paste("Coin Prices (2019)")) +
      geom_line() + 
      center_title +
      guides(col = guide_legend(ncol = 20)) +
      theme(legend.position = "bottom", legend.direction = "vertical")

# # Coin Volatility
# coins.volatility.corr <- round(cor(coins.volatility), 2)
# coins.volatility.corr.p <- round(cor_pmat(coins.volatility), 2)
# ggcorrplot(coins.volatility.corr, ggtheme = ggplot2::theme_bw(), p.mat = coins.volatility.corr.p, title = "Coin Volatility") +
#   theme_settings + center_title
# 
# # Coin Changes
# coins.changes.corr <- round(cor(coins.changes), 2)
# coins.changes.corr.p <- round(cor_pmat(coins.changes), 2)
# ggcorrplot(coins.changes.corr, ggtheme = ggplot2::theme_bw(), p.mat = coins.changes.corr.p, title = "Coin Changes") +
#   theme_settings + center_title
# 
# # Coin Returns
# coins.returns.corr <- round(cor(coins.returns), 2)
# coins.returns.corr.p <- round(cor_pmat(coins.returns), 2)
# ggcorrplot(coins.returns.corr, ggtheme = ggplot2::theme_bw(), p.mat = coins.returns.corr.p, title = "Coin Returns") +
#   theme_settings + center_title

```


Peri-COVID19
```{r}

ndays <- 362
coins.prices <- data.frame(matrix(nrow = ndays, ncol = 0))
coins.changes <- data.frame(matrix(nrow = ndays, ncol = 0))
coins.volumes <- data.frame(matrix(nrow = ndays, ncol = 0))
coins.returns <- data.frame(matrix(nrow = ndays, ncol = 0))
coins.volatility <- data.frame(matrix(nrow = ndays, ncol = 0))

price_cols <- c("Date", "Close", "Volume", "change", "returns", "volatility")
for (fname in list.files(paste("datasets/daily/coins", sep = "/"))) {
  symbol <- str_split(fname, "-", simplify = T)[1]
  values <- fread(paste("datasets/daily/coins", fname, sep = "/")) %>% as.data.frame() %>% filter(Date >= "2020-01-01" & Date <= "2020-12-31") %>% select(all_of(price_cols)) %>% arrange(Date) %>% fill(everything(), .direction = "downup")

  if (!any(is.na(values$Close))) {
    coins.prices$Date <- values$Date
    coins.prices[symbol] <- values$Close 
    coins.changes[symbol] <- values$change
    coins.returns[symbol] <- values$returns
    coins.volatility[symbol] <- values$volatility
  }
}

# Coin Prices
coins.prices.corr <- round(cor(coins.prices[-1]), 2)
coins.prices.corr.p <- round(ggcorrplot::cor_pmat(coins.prices[-1]), 2)
ggcorrplot(coins.prices.corr, pch.cex = 1, p.mat = coins.prices.corr.p, title = "Correlation in Coin Prices (2020)") +
  theme_settings + center_title

select_coin <- "ETH"
coins.prices.cor.mat <- cor_mat(coins.prices[-1])
coins.prices.cor.list <- cor_gather(coins.prices.cor.mat)
net <- coins.prices.cor.list %>% filter(var1 == select_coin & var2 != select_coin & abs(cor) > 0.5) %>% graph_from_data_frame(directed = F)
net <- simplify(net, remove.multiple = F, remove.loops = T) 
V(net)[name == select_coin]$color <- "grey"
V(net)[name != select_coin]$color <- "white"
E(net)$width <- 2 * abs(E(net)$cor)
E(net)$color <- "white"
E(net)[cor < 0.5]$color <- "blue"
E(net)[cor > 0.5]$color <- "red"
E(net)[p > 0.05]$linestyle <- 2
plot(net, layout = layout.kamada.kawai)

coins.prices[-1] <- scale(coins.prices[-1])
coins.prices.melt <- reshape2::melt(coins.prices, "Date", value.name = "Prices", variable.name = "Coins")
ggplot(data = coins.prices.melt, aes(x = Date, y = Prices, color = Coins)) +
      ggtitle(paste("Coin Prices (2020)")) +
      geom_line() + 
      center_title +
      guides(col = guide_legend(ncol = 20)) +
      theme(legend.position = "bottom", legend.direction = "vertical")

# # Coin Volatility
# coins.volatility.corr <- round(cor(coins.volatility), 2)
# coins.volatility.corr.p <- round(cor_pmat(coins.volatility), 2)
# ggcorrplot(coins.volatility.corr, ggtheme = ggplot2::theme_bw(), p.mat = coins.volatility.corr.p, title = "Coin Volatility") +
#   theme_settings + center_title
# 
# # Coin Changes
# coins.changes.corr <- round(cor(coins.changes), 2)
# coins.changes.corr.p <- round(cor_pmat(coins.changes), 2)
# ggcorrplot(coins.changes.corr, ggtheme = ggplot2::theme_bw(), p.mat = coins.changes.corr.p, title = "Coin Changes") +
#   theme_settings + center_title
# 
# # Coin Returns
# coins.returns.corr <- round(cor(coins.returns), 2)
# coins.returns.corr.p <- round(cor_pmat(coins.returns), 2)
# ggcorrplot(coins.returns.corr, ggtheme = ggplot2::theme_bw(), p.mat = coins.returns.corr.p, title = "Coin Returns") +
#   theme_settings + center_title

```


Post-COVID19
```{r}

ndays <- 304
coins.prices <- data.frame(matrix(nrow = ndays, ncol = 0))
coins.changes <- data.frame(matrix(nrow = ndays, ncol = 0))
coins.volumes <- data.frame(matrix(nrow = ndays, ncol = 0))
coins.returns <- data.frame(matrix(nrow = ndays, ncol = 0))
coins.volatility <- data.frame(matrix(nrow = ndays, ncol = 0))

price_cols <- c("Date", "Close", "Volume", "change", "returns", "volatility")
for (fname in list.files(paste("datasets/daily/coins", sep = "/"))) {
  symbol <- str_split(fname, "-", simplify = T)[1]
  values <- fread(paste("datasets/daily/coins", fname, sep = "/")) %>% as.data.frame() %>% filter(Date >= "2021-01-01") %>% select(all_of(price_cols)) %>% arrange(Date)  %>% fill(everything(), .direction = "downup")

  if (!any(is.na(values$Close))) {
    coins.prices$Date <- values$Date
    coins.prices[symbol] <- values$Close 
    coins.changes[symbol] <- values$change
    coins.returns[symbol] <- values$returns
    coins.volatility[symbol] <- values$volatility
  }
}

# Coin Prices
coins.prices.corr <- round(cor(coins.prices[-1]), 2)
coins.prices.corr.p <- round(ggcorrplot::cor_pmat(coins.prices[-1]), 2)
ggcorrplot(coins.prices.corr, pch.cex = 1, p.mat = coins.prices.corr.p, title = "Correlation in Coin Prices (2021)") +
  theme_settings + center_title

select_coin <- "ETH"
coins.prices.cor.mat <- cor_mat(coins.prices[-1])
coins.prices.cor.list <- cor_gather(coins.prices.cor.mat)
net <- coins.prices.cor.list %>% filter(var1 == select_coin & var2 != select_coin & abs(cor) > 0.5) %>% graph_from_data_frame(directed = F)
net <- simplify(net, remove.multiple = F, remove.loops = T) 
V(net)[name == select_coin]$color <- "grey"
V(net)[name != select_coin]$color <- "white"
E(net)$width <- 2 * abs(E(net)$cor)
E(net)$color <- "white"
E(net)[cor < 0.5]$color <- "blue"
E(net)[cor > 0.5]$color <- "red"
E(net)[p > 0.05]$linestyle <- 2
plot(net, layout = layout.kamada.kawai)

coins.prices[-1] <- scale(coins.prices[-1])
coins.prices.melt <- reshape2::melt(coins.prices, "Date", value.name = "Prices", variable.name = "Coins")
ggplot(data = coins.prices.melt, aes(x = Date, y = Prices, color = Coins)) +
      ggtitle(paste("Coin Prices (2021)")) +
      geom_line() + 
      center_title +
      guides(col = guide_legend(ncol = 20)) +
      theme(legend.position = "bottom", legend.direction = "vertical")

# # Coin Volatility
# coins.volatility.corr <- round(cor(coins.volatility), 2)
# coins.volatility.corr.p <- round(cor_pmat(coins.volatility), 2)
# ggcorrplot(coins.volatility.corr, ggtheme = ggplot2::theme_bw(), p.mat = coins.volatility.corr.p, title = "Coin Volatility") +
#   theme_settings
# 
# # Coin Changes
# coins.changes.corr <- round(cor(coins.changes), 2)
# coins.changes.corr.p <- round(cor_pmat(coins.changes), 2)
# ggcorrplot(coins.changes.corr, ggtheme = ggplot2::theme_bw(), p.mat = coins.changes.corr.p, title = "Coin Changes") +
#   theme_settings
# 
# # Coin Returns
# coins.returns.corr <- round(cor(coins.returns), 2)
# coins.returns.corr.p <- round(cor_pmat(coins.returns), 2)
# ggcorrplot(coins.returns.corr, ggtheme = ggplot2::theme_bw(), p.mat = coins.returns.corr.p, title = "Coin Returns") +
#   theme_settings


```

